### ISSUE TITLE
自从v0.4.0版本之后无法下载视频

### ISSUE THREAD

**Issue by The-vicissitudes-of-life** [oGsLP/kuaishou-crawler#11]
自从v0.4.0版本之后无法下载视频，全部都显示未找到视频，其他版本正常

**Comment by JH9601212** [comment]
同问  只是能查询到要爬的用户的视频名称，但是显示没有视频

**Comment by dd991** [comment]
同问0.4.0和0.4.1下载不了视频

**Comment by oGsLP** [comment]
已更新v0.5版本，修复视频获取链接，望周知

**Comment by ghost** [comment]
> 已更新v0.5版本，修复视频获取链接，望周知

ok,谢谢作者大大
