### ISSUE TITLE
抓取某一主题下的前一百位的用户信息，网页版有时候会跳出滑块验证码，请问有办法绕过吗？

### ISSUE THREAD

**Issue by redstoneleo** [oGsLP/kuaishou-crawler#13]
问个可能和本项目不相干的问题，请多多指教，谢谢！

比如说我要抓取“手工”主题下的前一百位的用户信息
https://live.kuaishou.com/search/author?keyword=%E6%89%8B%E5%B7%A5&page=1
网页版有时候会跳出滑块验证码，请问有办法绕过吗？

**Comment by oGsLP** [comment]
加上cookie['did']试试

**Comment by redstoneleo** [comment]
不起作用
