### ISSUE TITLE
关于v0.5.0输入did和用户id之后闪退的问题

### ISSUE THREAD

**Issue by ghost** [oGsLP/kuaishou-crawler#15]
打开ks.exe之后，大概下载了60个视频，软件闪退，之后重新打开输入did和用户id，回车之后闪退无法下载，在确保软件完整的情况下，切换过did，尝试过管理员运行以及将ks.exe放在非c盘目录，结果均无效，以下是错误截图:https://s1.ax1x.com/2020/08/11/aXNBSe.png

**Comment by oGsLP** [comment]
初步看，是did_web的cookie时效过期，不是说这个值会换会改变，是服务器那边检测到长时间未登录（不在线），认定cookie失效。为了保证爬取成功，在爬取的时候在浏览器中保持快手网页打开并登录。

**Comment by ghost** [comment]
好的，谢谢您的回答，我已经保持快手网页打开并登录，测试了两个ks账号，爬取到一半还是会闪退，然后就爬不了其他账号的视频了

**Comment by ghost** [comment]
问题已经解决，谢谢

**Comment by oGsLP** [comment]
能告诉我一下是什么原因导致的闪退吗
