### ISSUE TITLE
用户cookie中的did值

### ISSUE THREAD

**Issue by StarDream521** [oGsLP/kuaishou-crawler#7]
作者你好 我按你的方法获取了did值然后 输入了 用户的uid  
但是出现闪退的情况
我觉得可能我获取错了
可以仔细的给我讲解一下 
预先输入本用户cookie中的did值：  该填什么吗？

**Comment by oGsLP** [comment]
### ...

* 你好，请问你是不是把exe放在桌面跑的

* 写程序的时候用的是相对路径，本来下载图片应该是在当前目录的data文件夹下，但是windows在桌面跑的话会放在`C:\Windows\System32\`下而不是`C:\User\lenovo\Desktop`，而前者的目录下改写文件是需要管理员权限的，双击exe跑的话写文件没有权限会报错。刚才去测试了一下，在桌面跑是会闪退的，开管理员模式不会，但是文件保到前面的一个目录去了。

### 解决方法

* 建议把exe放入一个非C盘的一个文件夹里，然后运行
* 如果硬要在桌面运行
  * 右击exe选择以管理员身份运行
  * 或者win+r唤出cmd，`cd Desktop`, `ks.exe`两个命令运行


### 关于did

* 你在网页版快手登录并打开一个用户的一个作品，地址栏的链接大概是这样的形式，你把`did=`后面的保存下来就行，例如我随便一个账号登录后打开giao哥第一个视频，地址栏链接：
`https://live.kuaishou.com/u/3x4tn6nm8gnh9xk/3xgdj9s4it7rtce?did=web_67063b98a***********172acfa

* 要输入的就是`web_67063b98a***********172acfa`

**Comment by StarDream521** [comment]
![问题 (1)](https://user-images.githubusercontent.com/40490183/76924687-1b812e00-6912-11ea-9f0e-1afaffd317ec.png)
![问题 (2)](https://user-images.githubusercontent.com/40490183/76924688-1d4af180-6912-11ea-8503-847bab50a34d.png)
路径是E:\ks
已经以管理员 运行
但是还是显示闪退

**Comment by oGsLP** [comment]
刚才看了一下，好像是程序中根据数字id获取真实eid出现了问题，会尽快修改的。

## 快手号id、真实eid
* 这两个有什么区别呢，快手号id、真实eid都是系统分配给用户的一个初始值，id初始为一串数字，eid为字符串。用户一般可见的是id，可以修改的也是id，如果修改id，则会将eid也替换为id，此时id/eid是一样的。否则官方根据eid来标识用户。 
* 爬虫程序也是根据eid来爬取的，不过之前加了一个自动将id转化为eid的功能，现在好形象不能正确使用了，会尽快修改
* id/eid：修改后的id必须是非纯数字的字符串，如giao哥快手号146634318，就是一个未修改的数字id

## 如何根据id获得真实eid

* 在程序修复之前不是不可用的，解决方法就是，如果用户的id为纯数字，那么在网页版的用户主页，地址栏（如giao哥 `https://live.kuaishou.com/profile/3x4tn6nm8gnh9xk` ），则`3x4tn6nm8gnh9xk`为真实eid。在命令行id项输入此id代替数字id即可
* 当前可以先用这个方法爬取，会尽快修复程序的

**Comment by StarDream521** [comment]
好的谢谢！

**Comment by oGsLP** [comment]
* 修复了
* 从id到eid这一步，牵涉到的是一个cookie的问题，如果要完全模拟那个cookie的获得还是挺烦的，暂时用的值为None的键userId顶替一下，我这里测试没问题，应该可以用。
* 如果还是不好用的话，就麻烦手动打开主页查一下eid是啥吧0.0

**Comment by StarDream521** [comment]
谢谢作者，可以正常下载了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiaoyunfan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月18日(星期三) 中午1:50
收件人:&nbsp;"oGsLP/kuaishou-crawler"<kuaishou-crawler@noreply.github.com&gt;;
抄送:&nbsp;"私はあなたが好き⭐️🅥¹³¹"<1774057085@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [oGsLP/kuaishou-crawler] 用户cookie中的did值 (#7)





  
修复了
 
从id到eid这一步，牵涉到的是一个cookie的问题，如果要完全模拟那个cookie的获得还是挺烦的，暂时用的值为None的键userId顶替一下，我这里测试没问题，应该可以用。
 
如果还是不好用的话，就麻烦手动打开主页查一下eid是啥吧0.0
