### ISSUE TITLE
exe 版本会闪退

### ISSUE THREAD

**Issue by congtoubyby** [oGsLP/kuaishou-crawler#8]
首先感谢作者。
但是使用过程中发现，下载到 150 多个视频的时候，会自动闪退

**Comment by oGsLP** [comment]
请提供详细信息，或者用户id给我测试

**Comment by congtoubyby** [comment]
对象 ID：Fmj13188025266




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiaoyunfan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 中午1:07
收件人:&nbsp;"oGsLP/kuaishou-crawler"<kuaishou-crawler@noreply.github.com&gt;;
抄送:&nbsp;"张耀"<617304062@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [oGsLP/kuaishou-crawler] exe 版本会闪退 (#8)





 
请提供详细信息，或者用户id给我测试

**Comment by oGsLP** [comment]
![1](https://user-images.githubusercontent.com/34265146/79097413-53a15280-7d92-11ea-883f-8786210d6e82.jpg)
我测试没有任何问题，请保证是最新版本的exe，爬取过程中不要关闭登录的快手网站以免cookie失效

**Comment by congtoubyby** [comment]
exe 版本是最新的 0.4.1，我的系统版本是Win 10 专业版 11763.1098
不知道是不是我的环境的问题？请问你的系统版本是




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiaoyunfan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午2:23
收件人:&nbsp;"oGsLP/kuaishou-crawler"<kuaishou-crawler@noreply.github.com&gt;;
抄送:&nbsp;"张耀"<617304062@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [oGsLP/kuaishou-crawler] exe 版本会闪退 (#8)





 

 我测试没有任何问题，请保证是最新版本的exe，爬取过程中不要关闭登录的快手网站以免cookie失效

**Comment by congtoubyby** [comment]
我设置了一下 win8 的兼容模式，同时打开了管理员运行，好像就可以了

**Comment by oGsLP** [comment]
我也是win10，但是如果是环境问题，一开始就应该跑不了程序，不会说跑了一半出问题的

**Comment by oGsLP** [comment]
的确存在管理员权限的问题，请不要放在桌面或者c盘里面跑程序，会有文件(夹)读写权限的问题

**Comment by congtoubyby** [comment]
好的，多谢你！问题算是已经解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiaoyunfan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午3:01
收件人:&nbsp;"oGsLP/kuaishou-crawler"<kuaishou-crawler@noreply.github.com&gt;;
抄送:&nbsp;"张耀"<617304062@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [oGsLP/kuaishou-crawler] exe 版本会闪退 (#8)





 
的确存在管理员权限的问题，请不要放在桌面或者c盘里面跑程序，会有文件(夹)读写权限的问题
